#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr 17 15:27:57 2019

@author: alyssa
"""
import numpy as np

l = 3

def assign_third_batter(batting_average):
    for i in batting_average_array:
        max_batting_average = np.amax(batting_average)
        third_batter = batter_names[max_batting_average]
        return third_batter
        
def assign_1st_batter(stolen_bases, on_base):
    for i in stolen_bases:
        